### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Moarkill** [GabeRundlett/desktop-shadertoy#4] opened 2024-05-20 08:03 UTC
Launching the app results in a window opening but crashing directly afterwards. Output:
Failed to create the rml daxa raster pipeline. This should never happen, contact Gabe Rundlett
terminate called without an active exception
Aborted

App version: 0.4.1

I run ElementaryOS with spec:
Intel CPU, nvidia RTX gpu, 64GB RAM

Let me know if I can provide any more relevant information.

**Comment by RedNicStone** [comment] 2024-05-20 08:28
I can confirm this issue on fedora 39 with the 0.4.1 linux build.
The issue only seems to occur when running the application from a directory that is lower than the packaged directory.

**Comment by RedNicStone** [comment] 2024-05-20 08:40
@GabeRundlett The issue is [this commit](https://github.com/GabeRundlett/desktop-shadertoy/commit/e085647a1318977be476706b683ec325f2a18d8d) that changed the behavior of `get_resource_dir` for non-appimage builds.

When not building for appimage packaging the directory containing the binary should be returned, not an empty string. Either revert this change or modify the function to always return the directory containing the binary when not building for appimage packaging.

**Comment by Moarkill** [comment] 2024-05-20 14:45
Yes it works from the same dir :+1:

**Comment by GabeRundlett** [comment] 2024-05-20 14:49
Alright. I will make a new release (0.4.2) with the changes that RedNic had, which will allow you to run from any directory and close this issue

**Closed** 2024-05-20 15:25 UTC
